### ISSUE TITLE
阻塞问题：影子表创建以后执行curl.sh写入数据失败问题

### ISSUE THREAD

**Issue by jsfbetter** [shulieTech/Takin#108]
影子表已经按照要求配置好
![image](https://user-images.githubusercontent.com/17878613/149092343-b6b77fc0-ed3f-4637-b96a-f043db8eee5a.png)
数据库中已经新建好表
![image](https://user-images.githubusercontent.com/17878613/149092436-b60ad481-8b43-4ab2-b3f6-c2edd0e5d86a.png)
执行现象：没有新增记录，服务器报错如下
![image](https://user-images.githubusercontent.com/17878613/149092588-88eceeb5-62c3-4e24-94da-0fd7a5496bdf.png)
执行curl.sh的时候报错如下：

	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-embed-core-9.0.45.jar!/:na]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) [tomcat-embed-core-9.0.45.jar!/:na]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.45.jar!/:na]
	at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:59) [na:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_312]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.45.jar!/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_312]
Caused by: com.pamirs.pradar.exception.PressureMeasureError: ClusterTestSwitcherError: [addeasydemo-usercenter-1.0.0] datasource-0004 没有配置对应的影子表! url:jdbc:mysql://127.0.0.1:3306/easydemo_db, table:t_user, driverClassName:com.mysql.cj.jdbc.Driver, dbType:mysql

**Comment by jsfbetter** [comment]
如果覆盖影子库，使用？提示中配置，修改了ip，肯定会报错
![image](https://user-images.githubusercontent.com/17878613/149116843-2104e9af-4e82-4520-b759-75404724a392.png)

**Comment by jsfbetter** [comment]
如果有看到，辛苦帮忙看一下这种写入影子库失败的问题，谢谢

**Comment by jsfbetter** [comment]
是不是因为后面提供的agent的zip包会遇到这种问题？但是之前的agent包会有找不到应用的问题才进行的替换~

**Comment by zhang19970916** [comment]
你好，这个应该是属于配置问题

**Comment by zhang19970916** [comment]
agent包之前有符合开源镜像版本的，从报错来看没有拉取到影子表
