### ISSUE TITLE
easydemo-usercenter.jar运行异常

### ISSUE THREAD

**Issue by tree1024z** [shulieTech/Takin#129]
:: Spring Boot ::                (v2.4.5)

2022-05-19 10:15:48.415  INFO 10786 --- [           main] c.e.u.DemoUsercenterApplication          : Starting DemoUsercenterApplication v1.0-SNAPSHOT using Java 1.8.0_261 on devopsapp with PID 10786 (/root/easydemo/app/user/easydemo-usercenter.jar started by root in /root/easydemo/app/user)
2022-05-19 10:15:48.440  INFO 10786 --- [           main] c.e.u.DemoUsercenterApplication          : No active profile set, falling back to default profiles: default
2022-05-19 10:15:54.944  INFO 10786 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 28882 (http)
2022-05-19 10:15:54.963  INFO 10786 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-05-19 10:15:54.963  INFO 10786 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.45]
2022-05-19 10:15:55.075  INFO 10786 --- [           main] o.a.c.c.C.[.[localhost].[/user-center]   : Initializing Spring embedded WebApplicationContext
2022-05-19 10:15:55.076  INFO 10786 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 6210 ms
2022-05-19 10:15:56.587  INFO 10786 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2022-05-19 10:15:57.272  INFO 10786 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 28882 (http) with context path '/user-center'
@
"usercenter.log" 340L, 32169C
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.IllegalStateException: TTL logger implementation type is already set! type = 0
        at com.alibaba.ttl.threadpool.agent.internal.logging.Logger.setLoggerImplType(Logger.java:22)
        at com.alibaba.ttl.threadpool.agent.TtlAgent.premain(TtlAgent.java:128)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed
nohup: ignoring input
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.IllegalStateException: TTL logger implementation type is already set! type = 0
        at com.alibaba.ttl.threadpool.agent.internal.logging.Logger.setLoggerImplType(Logger.java:22)
        at com.alibaba.ttl.threadpool.agent.TtlAgent.premain(TtlAgent.java:128)
        ... 6 more

**Comment by zhang19970916** [comment]
这不是jar包的问题，看起来是agent，建议换个稳定的agent

**Comment by zhang19970916** [comment]
描述错误,是agent的问题，建议把agent日志贴出来
