### ISSUE TITLE
系统很多地方都会报null point 错误  系统现在没有登录了  但是很多地方还在使用 WebPluginUtils.getUser(); 获取出来是null

### ISSUE THREAD

**Issue by Fyuxuan** [shulieTech/Takin#93]
如标题 很多地方还是有 WebPluginUtils.getUser(); 相关代码。
但是获取出来是 null，导致会报错。
比如删除挡板提示删除失败，但是刷新页面发现挡板已经删除了。查看日志发现报 null point。

![image](https://user-images.githubusercontent.com/12712060/145160796-04c2268b-4270-4bb1-95d2-199e70acf29d.png)

![image](https://user-images.githubusercontent.com/12712060/145160658-615e2dce-13ee-4d16-8901-bc39dd505184.png)
```java
java.lang.NullPointerException: null
	at io.shulie.takin.web.biz.service.linkManage.impl.LinkGuardServiceImpl.deleteById(LinkGuardServiceImpl.java:140)
	at io.shulie.takin.web.entrypoint.controller.linkmanage.LinkGuardController.deleteGuard(LinkGuardController.java:166)
	at io.shulie.takin.web.entrypoint.controller.linkmanage.LinkGuardController$$FastClassBySpringCGLIB$$bb0b0d89.invoke(<generated>)
```
不仅仅是挡板这里，还有很多地方使用了 WebPluginUtils.getUser();

**Comment by Hezhongqi** [comment]
已修复！

**Comment by Hezhongqi** [comment]
拉取下新代码
